package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"graph-demo/graph/generated"
	"graph-demo/internal/dto"
)

// GetSystemHealth is the resolver for the getSystemHealth field.
func (r *mutationResolver) GetSystemHealth(ctx context.Context) (*dto.Health, error) {
	return &dto.Health{Status: "ok"}, nil
}

// GetSystemHealth is the resolver for the getSystemHealth field.
func (r *queryResolver) GetSystemHealth(ctx context.Context) (*dto.Health, error) {
	return &dto.Health{Status: "ok"}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
